#release configuration
#Sat Jul 26 02:40:04 AMT 2025
projectVersionPolicyId=default
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.org.springframework.samples\:spring-petclinic.connection=scm\:git@github.com\:Devkans/spring-petclinic.git
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.org.springframework.samples\:spring-petclinic.tag=HEAD
pinExternals=false
completedPhase=check-poms
scm.url=scm\:git\:git@github.com\:Devkans/spring-petclinic.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.org.springframework.samples\:spring-petclinic.url=git@github.com\:Devkans/spring-petclinic.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
exec.activateProfiles=github
pushChanges=true
project.scm.org.springframework.samples\:spring-petclinic.developerConnection=scm\:git\:git@github.com\:Devkans/spring-petclinic.git
scm.tag=pet-clinic-1.2
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
