name: Spring Petclinic CI/CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: argevorgyan/spring-petclinic
  PORT: 8080

jobs:
  pr-build:
    name: PR – Build & Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21 (cached Maven)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test (unit tests only)
        run: mvn -B clean test -DskipITs

  main-build-push:
    name: Main – Build & Push Docker Image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21 (cached Maven)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build application
        run: mvn -B clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          docker build \
            -t $IMAGE_NAME:$VERSION \
            -t $IMAGE_NAME:latest .

          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Deploy (placeholder)
        run: |
          echo "later steps "
